version: "2"

services:
  dev:
    build: .
    working_dir: /work
    volumes:
    - .:/work
    - ivy-cache:/root/.ivy2
    - docker-scala-sbt-cache:/root/.sbt
    entrypoint: []

volumes:
  ivy-cache:
    external: true
  docker-scala-sbt-cache:
    external: true
